### ISSUE TITLE
[Feature] Create master class with all the other one as field

### ISSUE THREAD

**Issue by bounty1342** [BirjuVachhani/spider#18]
Hey,

I think it would be easier to always import the same base class, with all the generated class as field>
 Then we can use `Class.subclass.img` to retrieve the image.

It would be even better, if this could match the directory :

- assets
  - images
    - root
      - logo_small.png
      - logo_full.png
    - onboarding
      - logo_small.png
      - logo_full.png
    - login
      - bar
        - bar.png
        - icon.png
      - button
        - icon.png
        - button.png
  - svg
    - 1 x
    - 2x

Then we can access `Assets.images.login.bar.icon` pretty easily.

1. Only one import to figure out
2. Easier to find the right image, without looking at the assets folder

Let me know what you thinks about it.
Regards

**Comment by BirjuVachhani** [comment]
@bounty1342 How do you propose to achieve this: `Assets.images.login.bar.icon`?

**Comment by bounty1342** [comment]
@BirjuVachhani : this is a very naive solution,
[Link](https://dartpad.dev/82af8a386e51984ddf57bd492775db0a)

This could surely be perfected.

**Comment by BirjuVachhani** [comment]
@bounty1342 
This makes sense but don't you think managing assets by screens or modules will complicate things like:
1. reusability - Although it can be reused easily, the path it represents tells a different story.
2. You have list all the folders in `pubspec.yaml`

**Comment by bounty1342** [comment]
Don't want to speak about everybody but my asset folder is already organized like this :
![image](https://user-images.githubusercontent.com/6307253/76218099-e1c66e00-6213-11ea-866e-a4dda4403672.png)

I presume one alternative could also be : `Assets.images_login_bar_icon`

If you want a file to be used by several view, you place it in the cross path (directory wise), or at the root...

**Comment by BirjuVachhani** [comment]
Closing this as I'm having no plans for this in near future.
