### ISSUE TITLE
Adobe XD Support

### ISSUE THREAD

**Issue by amreniouinnovent** [BirjuVachhani/spider#24]
I have used your library and it is really very helpful
Adobe XD Plugin for Flutter is released access early.
I think your library could be a great help in Adobe XD Plugin
They already using flutter_svg for svgs
And It would be great that they use your library.
Flutter XD Plugin
https://github.com/AdobeXD/xd-to-flutter-plugin

**Comment by BirjuVachhani** [comment]
@amreniouinnovent Thank you for this suggestion and thank you for finding this useful. I would be an honor if they use this package but it very unlikely for them to do so I guess. I haven't explored the XD plugin yet. Let me see what I can do...

**Comment by BirjuVachhani** [comment]
Closing this as I'm having no plan for this in near future.
