### ISSUE TITLE
Could we use flutter pub run build_runner build?

### ISSUE THREAD

**Issue by amorenew** [BirjuVachhani/spider#33]
I am not sure how the library is working
but do we need `spider build`, or we can use `flutter pub run build_runner build` ?

**Comment by amorenew** [comment]
This library is using build_runner but your library has more features
https://pub.dev/packages/assets_scanner

**Comment by BirjuVachhani** [comment]
@amorenew As of now, Spider doesn't support `build_runner`. Spider is a CLI tool that can be used independently without creating a dependency to your project.

Use `spider build` command to generate references.

I am closing this for now. Hope this will resolve your query. Feel free to reopen in case of further help.
