### ISSUE TITLE
Fails on Flutter 3.13

### ISSUE THREAD

**Issue by kaciula** [BirjuVachhani/spider#77]
I get this build error after updating to Flutter 3.13. Can you please fix it?

`Building package executable... 
Failed to build spider:spider:
../../../.pub-cache/hosted/pub.dev/watcher-1.0.2/lib/src/constructable_file_system_event.dart:7:57: Error: The class 'FileSystemEvent' can't be extended, implemented, or mixed in outside of its library because it's a sealed class.
abstract class _ConstructableFileSystemEvent implements FileSystemEvent {`

**Comment by BirjuVachhani** [comment]
What version of Spider are you using? You can check by running `spider -v`. Also try updating/reinstalling spider again!

**Comment by kaciula** [comment]
@BirjuVachhani I am using the latest version 4.2.2.

I have uninstalled and reinstalled spider and now it works. Thanks for the suggestion.

![Screenshot 2023-09-10 at 14 56 06](https://github.com/BirjuVachhani/spider/assets/18688/d0ae295a-9d61-4acf-8196-fbc2ec3ee426)

**Comment by BirjuVachhani** [comment]
@kaciula Yeah, this happens when Flutter is upgraded. Usually it is auto-fixed. I don't know why it did not for you! Glad it worked for you after reinstalling.
